# nixpacks.toml
[phases.setup]
nixPkgs = ["python310", "chromium", "chromedriver"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[variables]
# These help Chrome run in a restricted container environment
PYTHONUNBUFFERED = "1"
CHROME_PATH = "/usr/bin/google-chrome-stable"
