name: Daily Crawler

on:
  schedule:
    - cron: '6 * * * *'
  workflow_dispatch:

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
      # เช็คเอาต์โค้ดจาก Repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # ให้สิทธิ์ Execute กับ `start.sh`
      - name: Grant execute permission for start.sh
        run: chmod +x start.sh

      # ติดตั้ง Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # ติดตั้ง Google Chrome และ Chromedriver
      - name: Install Google Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip curl
          wget -q -O /tmp/chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i /tmp/chrome.deb || sudo apt-get -fy install
          rm /tmp/chrome.deb
          wget -q -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
          sudo unzip /tmp/chromedriver.zip -d /usr/local/bin/
          rm /tmp/chromedriver.zip

      # ติดตั้ง dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # รัน start.sh
      - name: Run crawler
        run: ./start.sh
